VERSION 1.0 CLASS
BEGIN
MultiUse = -1                                     'True
Persistable = 0                                   'NotPersistable
DataBindingBehavior = 0                           'vbNone
DataSourceBehavior  = 0                           'vbNone
MTSTransactionMode  = 0                           'NotAnMTSObject
END
Attribute VB_Name = "IDoknForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
' ===================================================================
' Class- IDoknForm.cls
' Description- Global DoknForm Implements
' Uses- A postback interface of form events to ControlManager to processes any additional requirements.
'====================================================================
'*****************************************************
Public Sub WinEvent(ByRef hWnd As Long, uMsg As Long, ByRef df As DokNForm, wParam As Long, lParam As Long)
'*****************************************************
   '
End Sub

' Yorgi's 4Matz [Feb 28,2007 23:58:51] sort=subs,vars;renum=procs,10;comments=50,50;AsType=40,25
